### ISSUE TITLE
Doesn't work with AOT?

### ISSUE THREAD

**Issue by billdwhite** [timdeschryver/ngrx-immer-example#1]
I've been using Immer with NGRX and just noticed that when I compile using AOT, the states are not loaded.  I downloaded your NGRX-Immer branch and when I start it with 'ng serve' it runs fine, but with 'ng run ngrx-immer:serve:production' it loads with no states.  I'm just curious if you'd run into this as well?

**Comment by timdeschryver** [comment]
Hi, I've just tried this and everything seems fine.
What exactly does `'ng run ngrx-immer:serve:production` do?	
Can you see errors in the console?

**Comment by billdwhite** [comment]
Are you using the "ngrx-immer" branch within the ngrx-immer repo?  That second command does "ahead of time" compilation based on the configuration in angular.json  It basically optimizes the codebase so that the browser doesn't have to do that much work on loading, resulting in a much faster app.  With 'ng serve' it only does the basic compilation and the browser does the rest or the work, which is good during development since ng serve compiles much much faster than doing a production build.   I just noticed that with AOT turned on, all of a sudden the Immer reducers do not work (at least for me); they just load with no state.  Any reducers I have that are not using Immer are fine. In the case of your demo app I get this (which is basically because the state is not there)
```

main.ce26860….js:1 ERROR TypeError: Cannot read property 'productSkus' of undefined
    at main.ce26860….js:1
    at main.ce26860….js:1
    at memoized (main.ce26860….js:1)
    at it (main.ce26860….js:1)
    at main.ce26860….js:1
    at memoized (main.ce26860….js:1)
    at main.ce26860….js:1
    at Array.map (<anonymous>)
    at it (main.ce26860….js:1)
    at main.ce26860….js:1
main.ce26860….js:1 ERROR TypeError: Cannot read property 'products' of undefined
    at main.ce26860….js:1
    at main.ce26860….js:1
    at memoized (main.ce26860….js:1)
    at it (main.ce26860….js:1)
    at main.ce26860….js:1
    at memoized (main.ce26860….js:1)
    at main.ce26860….js:1
    at Array.map (<anonymous>)
    at it (main.ce26860….js:1)
    at main.ce26860….js:1
﻿
```

​

**Comment by billdwhite** [comment]
One other thing to mention: this is not an issue with your demo code.  I just wanted to see if you were running into AOT problems with Immer used in NGRX like I was; you have one of the few demo apps that show how to use Immer with NGRX and NGXS so I tested your demo and it threw errors just like my own codebase was doing.  I just wanted to see if you had run into this as well.

**Comment by timdeschryver** [comment]
Aha, I was using the ngrx branch 😅 . I do get the same errors when using the immer branch.

**Comment by billdwhite** [comment]
ok, I was afraid of that.  You can also test it with just 'ng serve -aot' and you'll see the same thing.  The bad news is that it appears Immer can't be use with NGRX in production as long as this is happening.....

**Comment by timdeschryver** [comment]
I have a solution for this, give me a second and I'll commit it.

**Comment by timdeschryver** [comment]
It boils down that the compiler "expects" function reducer, instead of a `const` reducer.

**Comment by billdwhite** [comment]
ah! yes, that makes sense;  how did you troubleshoot that?  I wasn't able to figure out where to look...

**Comment by timdeschryver** [comment]
This commit https://github.com/timdeschryver/ngrx-immer/commit/8fc667990f123926ec37216add7be031078f69b5 fixes the prod build 😄

**Comment by timdeschryver** [comment]
Let us say, that I've encountered this problem before. And yes... it took a while before figuring it out.

**Comment by billdwhite** [comment]
thanks so much!! I'm wondering why the AOT breaks that but the normal dev server runtime does not...

**Comment by timdeschryver** [comment]
I believe there is a detailed thread in the Angular issues.
How's it using Immer in your case and why are you using it, if you don't mind me asking.

**Comment by billdwhite** [comment]
Actually, I'm using it because I read your [article](https://blog.angularindepth.com/clean-ngrx-reducers-using-immer-7fe4a0d43508) and it seemed like a good way to reduce the complexity I was facing in my NgRx reducers.  It worked great, until I tried to build it for production with AOT enabled and ran into this.  You saved me a lot of trouble :)

**Comment by timdeschryver** [comment]
Awesome, glad I could be of help 😄 
And thanks for creating this issue, I'm sure it can help others as well!
